[package]
name = "fast-neural-network"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
strip = true
# lto = true

# Enable only a small amount of optimization in debug mode
[profile.dev]
# opt-level = 1

[profile.release]
lto = "thin"

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
rayon = "1.7.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "parallel_vs_sequential"
harness = false